### ISSUE TITLE
Waffenauswahl implementieren

### ISSUE THREAD

**Issue by FlaShG** [AldebaranIndustries/ReiseNachAldebaran#1]

**Comment by pr0nopoly** [comment]
Wie wählt man denn eine Waffe aus? Im Post von Kl0tzfaust waren diese jeweils unter den Buttons 1-3. Werden die dann selected und man kann sie mit der Maus triggern oder benutzt man sie schon durch den Knopfdruck? Hat beides Vor- und Nachteile.
